#where the kitti datasets are on Nautilus
kitti : 
  raw_path : '/jbk001-data1/kitti_raw'
  vo_path_kitti : '/jbk001-data1/datasets/kitti/kitti_vo/vo_dataset/sequences'
  vo_path_tum : '/jbk001-data1/datasets/tum/' # tum
  procressed_data_path : '/jbk001-data1/kitti_vo/vo_dataset_processed'

#config details for the models
models : 
  if_pnp: False # default true
  if_deepF: True # default false
  trianflow : 
    match_num : 5000
    mode : 'depth_pose' 
    dataset : 'kitti_odo' 
    depth_match_num : 6000
    depth_sample_ratio : 0.20
    depth_scale : 1
    num_scales: 3
    h_flow_consist_alpha: 3.0
    h_flow_consist_beta: 0.05
    w_flow_error : 0.00
    is_frozen : True
    ransac_points : 6000 #we won't actually be using ransac (I hope at least)
#     pretrained : '/jbk001-data1/git/SuperPnP/TrianFlow/models/pretrained/kitti_odo.pth'
    pretrained : '/jbk001-data1/git/SuperPnP/TrianFlow/models/pretrained/depth_pose/iter_51999.pth'
  superpoint : 
    nms_radius: 4  
    keypoint_threshold: 0.05  
    max_keypoints: 1024  
  superglue: 
    weights: 'indoor' 
    sinkhorn_iterations: 20  
    match_threshold: 0.3
  attention:
    encoder_lr : 1e-5
    decoder_lr : 1e-4

    
#training hyperparameters 
num_iterations: 200000  
batch_size: 8 # 32
iter_start : 0 #place the iteration that it last stopped at here
num_workers : 6  
ransac_num_matches : 1000


#general
img_hw: [256, 832] #superglue used 480, 640
raw_hw : [370,1226]
