apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jbk001-data1-large
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi 
