apiVersion: batch/v1
kind: Job
metadata:
  name: jkang-superPnP 
  namespace: mc-lab 
  labels:
    user: jbk001 # Specify your name
spec:
  ttlSecondsAfterFinished: 86400  # Wait one day to delete completed jobs
  template:
    spec:
      containers:
      - name: gpu-container
        image: docker.io/yjau/nau-base:latest  # docker image
        command:
        - "zsh; cd /cephfs/yyjau/Documents/deepSfm; conda activate /cephfs/yyjau/.local/conda/envs/py36-torch1.1-deepsfm; ls"
        resources:
          requests:
            cpu: "16"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "16"
            memory: "32Gi"
            nvidia.com/gpu: 1
        volumeMounts:
          - name: cephfs-vol
            mountPath: /cephfs
          - name: dshm
            mountPath: /dev/shm 
      volumes:
      - name: dshm  # shared memory
        emptyDir:
          medium: Memory
      restartPolicy: Never
  backoffLimit: 2
